@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault

package dev.xkmc.l2serial.serialization.unified_processor;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;